version: '3.8'

services:
  bot:
    build: .
    container_name: pr_userbot
    restart: always
    volumes:
      # 1. Привязываем файл сессии (Вход) к серверу
      - ./user_session.session:/app/user_session.session
      # 2. Привязываем базу данных (Чаты) к серверу
      - ./app/data:/app/app/data
    env_file:
      - .env